config/routes.rb
Rails.application.routes.draw do
  root 'local_issues#index'
  resources :issues

  resources :local_issues do
    collection do
      get ":id/export", to: "local_issues#export", as: :export
    end
  end

  resources :sync, only: [:index]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/history.rb
class History < ActiveRecord::Base
 belongs_to :issue
end

app/models/issue.rb
class Issue < ActiveRecord::Base
 belongs_to :project
 has_many :histories
  def self.sync_from_api
   DoneDoneApi.sync_issues
  end
end

app/models/local_issue.rb
class LocalIssue < ApplicationRecord

  def self.create_issue(local_issue_id)
    DoneDoneApi.export_issues(local_issue_id)
   end
end

app/models/project.rb
class Project < ActiveRecord::Base
 has_many :issues

  def self.sync_from_api
   DoneDoneApi.sync_projects
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/issues_controller.rb
class IssuesController < ApplicationController
  def index
    @issues = Issue.order(last_updated_on: :desc)
    @issue = Issue.all
    @ready_issue = Issue.all
    @ready_issue_title = @ready_issue.pluck(:title)
  end

  def show
    @issue = Issue.find(params[:id])
    @histories = @issue.histories.order(:created_on)
  end

  def new
    @issue = Issue.new
  end

  def edit
    @issue = Issue.find(params[:id])
  end


  def create
  @issue = Issue.new
  respond_to do |format|
      if @issue.save
        format.html { redirect_to @issue, notice: 'Issue was successfully created.' }
        format.json { render :show, status: :created, location: @issue }
      else
        format.html { render :new }
        format.json { render json: @issue.errors, status: :unprocessable_entity }
      end
    end
  end
end

app/controllers/local_issues_controller.rb
class LocalIssuesController < ApplicationController
  before_action :set_local_issue, only: [:show, :edit, :update, :destroy]

  # GET /local_issues
  # GET /local_issues.json
  def index
    @local_issues = LocalIssue.all
  end

  # GET /local_issues/1
  # GET /local_issues/1.json
  def show
  end

  # GET /local_issues/new
  def new
    @local_issue = LocalIssue.new
  end

  # GET /local_issues/1/edit
  def edit
  end

  # POST /local_issues
  # POST /local_issues.json
  def create
    @local_issue = LocalIssue.new(local_issue_params)

    respond_to do |format|
      if @local_issue.save
        format.html { redirect_to @local_issue, notice: 'Local issue was successfully created.' }
        format.json { render :show, status: :created, location: @local_issue }
      else
        format.html { render :new }
        format.json { render json: @local_issue.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /local_issues/1
  # PATCH/PUT /local_issues/1.json
  def update
    respond_to do |format|
      if @local_issue.update(local_issue_params)
        format.html { redirect_to @local_issue, notice: 'Local issue was successfully updated.' }
        format.json { render :show, status: :ok, location: @local_issue }
      else
        format.html { render :edit }
        format.json { render json: @local_issue.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /local_issues/1
  # DELETE /local_issues/1.json
  def destroy
    @local_issue.destroy
    respond_to do |format|
      format.html { redirect_to local_issues_url, notice: 'Local issue was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def export
    response = LocalIssue.create_issue(params[:id])
    if response.body
      respond_to do |format|
          format.html { redirect_to local_issues_path, notice: 'Local issue was successfully export.' }
          format.json { render :show, status: :ok, location: @local_issue }
      end
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_local_issue
      @local_issue = LocalIssue.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def local_issue_params
      params.require(:local_issue).permit(:title, :desription, :priority_level_id, :fixer_id, :tester_id)
    end
end

app/controllers/sync_controller.rb
class SyncController < ApplicationController
  def index
    Project.sync_from_api
    Issue.sync_from_api

    redirect_to root_url
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/issues_helper.rb
module IssuesHelper
end

app/helpers/local_issues_helper.rb
module LocalIssuesHelper
end

app/helpers/sync_helper.rb
module SyncHelper
end

app/views/issues/_form.html.erb
<%= form_for(@issue, html: { multipart: :true, class: "form" }) do |form| %>
  <% if @issue.errors.any? %>
    <div>
      <h2><%= pluralize(@issue.errors.count, "error") %> prohibited this issue from being saved:</h2>

      <ul>
      <% @issue.errors.full_messages.each do |message| %>
        <%= message %>
      <% end %>
      </ul>
    </div>
  <% end %>

    <div>
    <%= form.collection_select :project_id, Project.all, :id, :title %><br />
    </div>

    <div>
    <%= form.text_field :title, placeholder: :title %><br />
    </div>

    <div>
    <%= form.text_field :description, placeholder: :desription %><br />
    </div>

    <div>
    <%= form.text_field :priority, placeholder: :priority %><br />
    </div>

    <div>
    <%= form.text_field :tester, placeholder: :tester %><br />
    </div>

    <div>
    <%= form.text_field :fixer, placeholder: :fixer %>
    </div>

    <table>
    <ul>
    <tr>
    <td><%= form.submit "Submit" %></td>
    <td><%= link_to "Back", :back %></td>
    </tr>
    </ul>
    </table>
<% end %>

app/views/issues/edit.html.erb
<center><h2> Edit </h2>

<%= render "form", issue: @issues %>

app/views/issues/index.html.erb
<% if @issues.any? %>
 <h2>Issues</h2>
 <table class="table table-striped">
 <thead>
 <tr>
 <th>Project</th>
 <th>Priority</th>
 <th>Title</th>
 <th>Status</th>
 <th>Fixer</th>
 <th>Tester</th>
 </tr>
 </thead>
 <tbody>
 <% @issues.each do |issue| %>
 <tr>
 <td><%= issue.project.title %></td>
 <td><span class="label label-<%= issue.priority.downcase %>"><%= issue.priority %></span></td>
 <td><strong><%= link_to '#' + issue.order_number.to_s + ': ' + issue.title, issue %></strong></td>
 <td><%= issue.status %></td>
 <td><%= issue.tester %></td>
 <td><%= issue.fixer %></td>
 </tr>
 </tbody>
 </table><br />
   <% end %>

  <td><%= link_to 'Create Issue', new_local_issue_path %></td><br />
  <td><%= link_to 'Local Issue', local_issues_path %></td><br />
  <td><%= link_to 'Import Issues', sync_index_path %></td><br />
  <td><%= link_to "Back", :back %></td><br />
<% end %>

app/views/issues/new.html.erb
<center><h1>New Issue</h1>

<%= render 'form', locals: { issue: @issues } %>

app/views/issues/show.html.erb
<div class="col-md-8">

 <ul class="list-inline">
 <li>#<%= @issue.order_number %></li>
 <li><span class="label label-<%= @issue.priority.downcase %>"><%= @issue.priority %></span></li>
 <li><%= @issue.status %></li>
 <% if @issue.due_date %>
 <li>Due <%= @issue.due_date %></li>
 <% end %>
 </ul>
 <h1><%= @issue.title %></h1>
 <hr />

 <p><%= @issue.description.html_safe %></p>

 <hr />

 <% @histories.each do |h| %>

 <div class="panel panel-default">
 <div class="panel-heading">
 <h6><%= h.created_on %></h6>
 <h4><%= h.action %></h4>
 </div>
 <div class="panel-body">
 <%= h.description.html_safe %>
 </div>
 </div>

 <% end %>

 </div>

 <div class="col-md-4">
 <table class="table">
 <tbody>
 <tr>
 <th>Project</th>
 <td><%= @issue.project.title %></td>
 </tr>
 <tr>
 <th>Fixer</th>
 <td><%= @issue.fixer %></td>
 </tr>
 <tr>
 <th>Tester</th>
 <td><%= @issue.tester %></td>
 </tr>
 <tr>
 <th>Created</th>
 <td><%= @issue.created_on %><br />by <%= @issue.creator %></td>
 </tr>
 <tr>
 <th>Last Updated</th>
 <td><%= @issue.last_updated_on %><br />by <%= @issue.last_updater %></td>
 </tr>
 </tbody>
 </table>
 </div>
</div>

<%= link_to "Edit", edit_issue_path(@issue) %>
<%= link_to "Back", root_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Donedone</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div class="container">
     <div class="row">
     <div class="col-md-12">
     <%= yield %>
     </div>
     </div>
    </div>
  </body>
</html>

app/views/local_issues/_form.html.erb
<%= form_for(local_issue) do |f| %>
  <% if local_issue.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(local_issue.errors.count, "error") %> prohibited this local_issue from being saved:</h2>

      <ul>
      <% local_issue.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %>
    <%= f.text_field :title %>
  </div>

  <div class="field">
    <%= f.label :desription %>
    <%= f.text_field :desription %>
  </div>

  <div class="field">
    <%= f.label :priority_level_id %>
    <%= f.select :priority_level_id,
      [['Low', 1], ['Medium', 2], ['High', 3], ['Critical', 4]]
    %>
  </div>

  <div class="field">
    <%= f.label :fixer_id %>
    <%= f.select :fixer_id,
      [['Mariano Italiano', 139283]] %>
  </div>

  <div class="field">
    <%= f.label :tester_id %>
    <%= f.select :tester_id,
      [['Mariano Italiano', 139283]]  %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/local_issues/edit.html.erb
<h1>Editing Local Issue</h1>

<%= render 'form', local_issue: @local_issue %>

<%= link_to 'Show', @local_issue %> |
<%= link_to 'Back', local_issues_path %>

app/views/local_issues/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Local Issues</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Desription</th>
      <th>Priority level</th>
      <th>Fixer</th>
      <th>Tester</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @local_issues.each do |local_issue| %>
      <tr>
        <td><%= local_issue.title %></td>
        <td><%= local_issue.desription %></td>
        <td><%= local_issue.priority_level_id %></td>
        <td><%= local_issue.fixer_id %></td>
        <td><%= local_issue.tester_id %></td>
        <td><%= link_to 'Show', local_issue %></td>
        <td><%= link_to 'Edit', edit_local_issue_path(local_issue) %></td>
        <td><%= link_to 'Destroy', local_issue, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<td><%= link_to 'New Local Issue', new_local_issue_path %></td><br />
<td><%= link_to 'Online Issues', issues_path %></td><br />
<td><%= link_to 'Import Issues', sync_index_path %></td><br />
<td><%= link_to "Back", :back %></td><br />

app/views/local_issues/new.html.erb
<h1>New Local Issue</h1>

<%= render 'form', local_issue: @local_issue %>

<%= link_to 'Back', local_issues_path %>

app/views/local_issues/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @local_issue.title %>
</p>

<p>
  <strong>Desription:</strong>
  <%= @local_issue.desription %>
</p>

<p>
  <strong>Priority level:</strong>
  <%= @local_issue.priority_level_id %>
</p>

<p>
  <strong>Fixer:</strong>
  <%= @local_issue.fixer_id %>
</p>

<p>
  <strong>Tester:</strong>
  <%= @local_issue.tester_id %>
</p>

<%= link_to "Export", export_local_issues_path(@local_issue) %>

<%= link_to 'Edit', edit_local_issue_path(@local_issue) %> |
<%= link_to 'Back', local_issues_path %>